version: '3'

services:
  web:
    build: .
    ports:
      - "3000:80"
    environment:
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/myapp_production
    depends_on:
      - db
    volumes:
      - ./storage:/rails/storage
    restart: unless-stopped

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=myapp_production
    restart: unless-stopped

volumes:
  postgres_data:
