# PostgreSQL configuration
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] || 'postgresql://postgres@localhost/aidd_development' %>
  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://postgres@localhost/aidd_development' %>
  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://postgres@localhost/aidd_development' %>

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] || 'postgresql://postgres@localhost/aidd_test' %>
  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://postgres@localhost/aidd_test' %>
  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://postgres@localhost/aidd_test' %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

